/* Generated by tools/generate_aot_ebin.py; do not edit manually.
 * E.BIN sha256: 9d13aa4593d97b790afc37d73da8be985e7a3aa7f3dcfe6b91c798671067aa5e
 */

#if defined(S6502_AOT_DEFINE_DATA)
typedef struct s6502_aot_block {
    uint32_t physical_pc;
    uint16_t virtual_pc;
    uint16_t signature_offset;
    uint8_t signature_size;
    uint8_t instruction_count;
    uint8_t requires_bank2;
} s6502_aot_block_t;

#define S6502_AOT_BLOCK_COUNT 46u
static const uint8_t s6502_aot_signature[] = {
    0x38, 0xad, 0x3a, 0x00, 0xe9, 0x20, 0x8d, 0x3a, 0x00, 0xad, 0x3b, 0x00,
    0xe9, 0x00, 0x8d, 0x3b, 0x00, 0x38, 0xad, 0x38, 0x00, 0xe9, 0x20, 0x8d,
    0x38, 0x00, 0xad, 0x39, 0x00, 0xe9, 0x00, 0x8d, 0x39, 0x00, 0x60, 0xa9,
    0x05, 0x85, 0x0c, 0xad, 0x00, 0x20, 0x0a, 0xaa, 0xa9, 0x00, 0x2a, 0xa8,
    0x8a, 0x0a, 0xaa, 0x98, 0x2a, 0xa8, 0x8a, 0x18, 0x6d, 0x01, 0x20, 0x85,
    0x0d, 0x98, 0x6d, 0x02, 0x20, 0x85, 0x0e, 0x8d, 0x00, 0x20, 0xa5, 0x0d,
    0xe6, 0x0c, 0x18, 0x69, 0x01, 0x85, 0x0d, 0xa9, 0x00, 0x6d, 0x00, 0x20,
    0x85, 0x0e, 0x8d, 0x00, 0x20, 0xa5, 0x0d, 0xe6, 0x0c, 0x18, 0x69, 0x01,
    0x85, 0x0d, 0xa9, 0x00, 0x6d, 0x00, 0x20, 0x85, 0x0e, 0x8d, 0x00, 0x20,
    0xa5, 0x0d, 0xe6, 0x0c, 0x18, 0x69, 0x01, 0x85, 0x0d, 0xa9, 0x00, 0x6d,
    0x00, 0x20, 0x85, 0x0e, 0x8d, 0x00, 0x20, 0x68, 0xa8, 0x68, 0xaa, 0x28,
    0x60, 0x8a, 0xa8, 0xb1, 0x2f, 0x8d, 0xb3, 0x20, 0xc8, 0xb1, 0x2f, 0x8d,
    0xb4, 0x20, 0xa9, 0x00, 0x8d, 0xb5, 0x20, 0xac, 0x8b, 0x20, 0xa9, 0x00,
    0x8d, 0xe5, 0x20, 0xa9, 0xff, 0x8d, 0xe6, 0x20, 0xc0, 0x00, 0xf0, 0x15,
    0xa5, 0x03, 0x91, 0x2f, 0xc8, 0xca, 0x4c, 0x33, 0x79, 0xa0, 0x00, 0xb1,
    0x3a, 0x2d, 0xe5, 0x20, 0x0d, 0xb3, 0x20, 0x91, 0x3a, 0xc8, 0xad, 0xb4,
    0x20, 0x91, 0x3a, 0xc8, 0xb1, 0x3a, 0x2d, 0xe6, 0x20, 0x0d, 0xb5, 0x20,
    0x91, 0x3a, 0x20, 0x46, 0x66, 0x8a, 0xa8, 0xb1, 0x2f, 0x8d, 0xb3, 0x20,
    0xa9, 0x00, 0x8d, 0xb4, 0x20, 0xac, 0x8b, 0x20, 0xa9, 0x00, 0x8d, 0xe5,
    0x20, 0xa9, 0xff, 0x8d, 0xe6, 0x20, 0xc0, 0x00, 0xf0, 0x13, 0xa0, 0x00,
    0xb1, 0x2f, 0x8d, 0xe5, 0x20, 0x18, 0xad, 0x2f, 0x00, 0x69, 0x01, 0x8d,
    0x2f, 0x00, 0xad, 0x30, 0x00, 0x69, 0x00, 0x8d, 0x30, 0x00, 0xa0, 0x00,
    0xb1, 0x2f, 0x8d, 0xe6, 0x20, 0xad, 0xcf, 0x20, 0xaa, 0xe0, 0x00, 0xf0,
    0x0b, 0x18, 0xad, 0x3a, 0x00, 0x69, 0x20, 0x8d, 0x3a, 0x00, 0xad, 0x3b,
    0x00, 0x69, 0x00, 0x8d, 0x3b, 0x00, 0x18, 0xad, 0x38, 0x00, 0x69, 0x20,
    0x8d, 0x38, 0x00, 0xad, 0x39, 0x00, 0x69, 0x00, 0x8d, 0x39, 0x00, 0x60,
    0xa0, 0x00, 0xa9, 0x00, 0x91, 0x3a, 0x18, 0xad, 0x3a, 0x00, 0x69, 0x01,
    0x8d, 0x3a, 0x00, 0xad, 0x3b, 0x00, 0x69, 0x00, 0x8d, 0x3b, 0x00, 0xce,
    0xd8, 0x20, 0xad, 0xd8, 0x20, 0xc9, 0x00, 0xd0, 0xa7, 0xa0, 0x00, 0xad,
    0xe6, 0x20, 0x91, 0x3a, 0x18, 0xad, 0x3a, 0x00, 0x69, 0x01, 0x8d, 0x3a,
    0x00, 0xad, 0x3b, 0x00, 0x69, 0x00, 0x8d, 0x3b, 0x00, 0xce, 0xd8, 0x20,
    0xad, 0xd8, 0x20, 0xc9, 0x00, 0xf0, 0x03, 0x8d, 0xb7, 0x20, 0x18, 0xa9,
    0x01, 0x6d, 0x3a, 0x00, 0x8d, 0x3a, 0x00, 0xa9, 0x00, 0x6d, 0x3b, 0x00,
    0x8d, 0x3b, 0x00, 0x4c, 0x22, 0x88, 0xa0, 0x00, 0xb1, 0x3a, 0x2d, 0xe5,
    0x20, 0x0d, 0xb3, 0x20, 0x91, 0x3a, 0xc8, 0xb1, 0x3a, 0x2d, 0xe6, 0x20,
    0x0d, 0xb4, 0x20, 0x91, 0x3a, 0x20, 0x46, 0x66, 0xe0, 0x00, 0xf0, 0x09,
    0xad, 0x82, 0x20, 0xc9, 0x40, 0x90, 0x2b, 0x0e, 0x89, 0x20, 0x2e, 0x8a,
    0x20, 0x2e, 0x85, 0x20, 0x2e, 0x86, 0x20, 0x90, 0x18, 0x0e, 0x89, 0x20,
    0x2e, 0x85, 0x20, 0x90, 0x0f, 0xa9, 0x00, 0x8d, 0x00, 0x20, 0xa5, 0x0d,
    0x38, 0xed, 0xd6, 0x03, 0xaa, 0xa5, 0x0e, 0xed, 0xd5, 0x03, 0x4a, 0xa8,
    0x8a, 0x6a, 0xaa, 0x98, 0x4a, 0x8a, 0x6a, 0x18, 0x6d, 0x00, 0x20, 0x8d,
    0x00, 0x20, 0x68, 0xa8, 0x68, 0xaa, 0xad, 0x00, 0x20, 0x28, 0x60, 0xee,
    0x82, 0x20, 0xe8, 0xe8, 0x4c, 0x86, 0x60, 0x88, 0xd0, 0xe6, 0xa0, 0x00,
    0xb1, 0x20, 0x31, 0x23, 0xa0, 0x08, 0x91, 0x2a, 0xa0, 0x01, 0xb1, 0x20,
    0x31, 0x23, 0xa0, 0x09, 0x91, 0x2a, 0xa0, 0x02, 0xb1, 0x20, 0x31, 0x23,
    0xa0, 0x0a, 0x91, 0x2a, 0xa0, 0x03, 0xb1, 0x20, 0x31, 0x23, 0xa0, 0x0b,
    0x91, 0x2a, 0x20, 0x96, 0xd5, 0x08, 0x78, 0x8d, 0x00, 0x20, 0x8a, 0x48,
    0x98, 0x48, 0xad, 0x00, 0x20, 0xc9, 0xe0, 0xb0, 0x0f, 0xad, 0x81, 0x20,
    0xc9, 0x90, 0xd0, 0x03, 0x38, 0xad, 0xb7, 0x20, 0xe9, 0x08, 0x90, 0x5d,
    0xad, 0x81, 0x20, 0xc9, 0x08, 0x90, 0x66, 0xad, 0xe5, 0x03, 0xc9, 0x01,
    0xd0, 0x37, 0xad, 0x3b, 0x00, 0xcd, 0xe7, 0x03, 0xd0, 0x2f, 0x18, 0xad,
    0x87, 0x20, 0x6d, 0x89, 0x20, 0x8d, 0x89, 0x20, 0x90, 0x03, 0xa8, 0x38,
    0xa5, 0x26, 0xe9, 0x01, 0x85, 0x26, 0xa5, 0x27, 0xe9, 0x00, 0x85, 0x27,
    0x48, 0xa5, 0x26, 0x48, 0x98, 0x60, 0xad, 0xe5, 0x03, 0xc9, 0x01, 0xd0,
    0x32, 0xad, 0x3b, 0x00, 0xcd, 0xe7, 0x03, 0xd0, 0x2a, 0x48, 0x18, 0xa5,
    0x2a, 0x69, 0x08, 0x85, 0x20, 0xa5, 0x2b, 0x69, 0x00, 0x85, 0x21, 0x68,
    0x60, 0xa2, 0x00, 0xa5, 0x20, 0x38, 0xe5, 0x23, 0xf0, 0x03, 0x08, 0xe8,
    0x28, 0xa5, 0x21, 0xe5, 0x24, 0xf0, 0x03, 0x08, 0xe8, 0x28, 0x08, 0x68,
    0x09, 0x02, 0xe0, 0x00, 0xf0, 0x02, 0x29, 0xfd, 0x48, 0x28, 0x60, 0x4c,
    0x75, 0x6a, 0xa0, 0x00, 0xb1, 0x2f, 0x8d, 0xe5, 0x20, 0x18, 0xad, 0x2f,
    0x00, 0x69, 0x01, 0x8d, 0x2f, 0x00, 0xad, 0x30, 0x00, 0x69, 0x00, 0x8d,
    0x30, 0x00, 0xa0, 0x00, 0xb1, 0x2f, 0x8d, 0xe6, 0x20, 0xad, 0xcf, 0x20,
    0xaa, 0xe0, 0x00, 0xf0, 0x0b, 0x18, 0xad, 0x2f, 0x00, 0x69, 0x01, 0x8d,
    0x2f, 0x00, 0xad, 0x30, 0x00, 0x69, 0x00, 0x8d, 0x30, 0x00, 0xad, 0xe9,
    0x20, 0x8d, 0x3a, 0x00, 0xad, 0xea, 0x20, 0x8d, 0x3b, 0x00, 0x20, 0x46,
    0x66, 0x38, 0xe9, 0xe0, 0x8d, 0x00, 0x20, 0xad, 0x29, 0x20, 0x8d, 0x01,
    0x20, 0xad, 0x2a, 0x20, 0x8d, 0x02, 0x20, 0xa9, 0x05, 0x85, 0x0c, 0xad,
    0x00, 0x20, 0x0a, 0xaa, 0xa9, 0x00, 0x2a, 0xa8, 0x8a, 0x0a, 0xaa, 0x98,
    0x2a, 0xa8, 0x8a, 0x18, 0x6d, 0x01, 0x20, 0x85, 0x0d, 0x98, 0x6d, 0x02,
    0x20, 0x85, 0x0e, 0x8d, 0x00, 0x20, 0xa5, 0x0d, 0xe6, 0x0c, 0x18, 0x69,
    0x01, 0x85, 0x0d, 0xa9, 0x00, 0x6d, 0x00, 0x20, 0x85, 0x0e, 0x8d, 0x00,
    0x20, 0xa5, 0x0d, 0xe6, 0x0c, 0x18, 0x69, 0x01, 0x85, 0x0d, 0xa9, 0x00,
    0x6d, 0x00, 0x20, 0x85, 0x0e, 0x8d, 0x00, 0x20, 0xa5, 0x0d, 0xe6, 0x0c,
    0x18, 0x69, 0x01, 0x85, 0x0d, 0xa9, 0x00, 0x6d, 0x00, 0x20, 0x85, 0x0e,
    0x8d, 0x00, 0x20, 0x68, 0xa8, 0x68, 0xaa, 0x28, 0x60, 0xa0, 0x02, 0xb1,
    0x28, 0x85, 0x20, 0xc8, 0xb1, 0x28, 0x85, 0x21, 0xa0, 0x00, 0xa5, 0x20,
    0x91, 0x28, 0xc8, 0xa5, 0x21, 0x91, 0x28, 0x18, 0xa5, 0x20, 0x69, 0x01,
    0x85, 0x20, 0xa5, 0x21, 0x69, 0x00, 0x85, 0x21, 0xa0, 0x02, 0xa5, 0x20,
    0x91, 0x28, 0xc8, 0xa5, 0x21, 0x91, 0x28, 0xa0, 0x00, 0xb1, 0x28, 0x85,
    0x23, 0xc8, 0xb1, 0x28, 0x85, 0x24, 0xa0, 0x06, 0xb1, 0x28, 0xa0, 0x00,
    0x91, 0x23, 0xa0, 0x04, 0x38, 0xb1, 0x28, 0xe9, 0x01, 0x91, 0x28, 0xc8,
    0xb1, 0x28, 0xe9, 0x00, 0x91, 0x28, 0x4c, 0x10, 0x50, 0xa0, 0x00, 0xb1,
    0x31, 0x2d, 0xe3, 0x20, 0x0d, 0xe6, 0x20, 0x91, 0x31, 0x18, 0xad, 0x31,
    0x00, 0x69, 0x01, 0x8d, 0x31, 0x00, 0xad, 0x32, 0x00, 0x69, 0x00, 0x8d,
    0x32, 0x00, 0xce, 0xd8, 0x20, 0xad, 0xd8, 0x20, 0xc9, 0x00, 0xf0, 0x52,
    0xa0, 0x00, 0xb1, 0x2f, 0x8d, 0xe5, 0x20, 0x18, 0xad, 0x2f, 0x00, 0x69,
    0x01, 0x8d, 0x2f, 0x00, 0xad, 0x30, 0x00, 0x69, 0x00, 0x8d, 0x30, 0x00,
    0xa0, 0x00, 0xb1, 0x2f, 0x8d, 0xe6, 0x20, 0xad, 0xcf, 0x20, 0xaa, 0xe0,
    0x00, 0xf0, 0x0b, 0x4e, 0xe5, 0x20, 0x6e, 0xe6, 0x20, 0xca, 0xe0, 0x00,
    0xd0, 0xf5, 0xad, 0xe6, 0x20, 0x91, 0x31, 0x18, 0xad, 0x31, 0x00, 0x69,
    0x01, 0x8d, 0x31, 0x00, 0xad, 0x32, 0x00, 0x69, 0x00, 0x8d, 0x32, 0x00,
    0xce, 0xd8, 0x20, 0xad, 0xd8, 0x20, 0xc9, 0x00, 0xd0, 0xae, 0xa0, 0x00,
    0xb1, 0x2f, 0x8d, 0xe5, 0x20, 0x18, 0xad, 0x2f, 0x00, 0x69, 0x01, 0x8d,
    0x2f, 0x00, 0xad, 0x30, 0x00, 0x69, 0x00, 0x8d, 0x30, 0x00, 0xa0, 0x00,
    0xb1, 0x2f, 0x8d, 0xe6, 0x20, 0xad, 0xcf, 0x20, 0xaa, 0xe0, 0x00, 0xf0,
    0x0b, 0x18, 0xad, 0x2f, 0x00, 0x69, 0x01, 0x8d, 0x2f, 0x00, 0xad, 0x30,
    0x00, 0x69, 0x00, 0x8d, 0x30, 0x00, 0x18, 0xad, 0xde, 0x20, 0x6d, 0x31,
    0x00, 0x8d, 0x31, 0x00, 0xa9, 0x00, 0x6d, 0x32, 0x00, 0x8d, 0x32, 0x00,
    0xce, 0xda, 0x20, 0xad, 0xda, 0x20, 0xc9, 0x00, 0xf0, 0x03,
};

static const s6502_aot_block_t s6502_aot_blocks[] = {
    {0xeb5678u, 0x6678u, 0u, 35u, 15u, 0u},
    {0xeaa55bu, 0xf55bu, 35u, 98u, 55u, 1u},
    {0xeb508au, 0x608au, 133u, 35u, 16u, 1u},
    {0xebe937u, 0x7937u, 168u, 9u, 5u, 0u},
    {0xeb5111u, 0x6111u, 177u, 32u, 14u, 1u},
    {0xeb550fu, 0x650fu, 209u, 29u, 13u, 1u},
    {0xeb5a75u, 0x6a75u, 238u, 39u, 17u, 1u},
    {0xeb5655u, 0x6655u, 277u, 35u, 15u, 0u},
    {0xeb6233u, 0x7233u, 312u, 33u, 14u, 1u},
    {0xeb5ae0u, 0x6ae0u, 345u, 34u, 14u, 1u},
    {0xeb782au, 0x882au, 379u, 23u, 9u, 1u},
    {0xeb55a0u, 0x65a0u, 402u, 26u, 11u, 1u},
    {0xebe933u, 0x7933u, 428u, 4u, 2u, 0u},
    {0xeb5646u, 0x6646u, 432u, 7u, 3u, 1u},
    {0xeb6bd4u, 0x7bd4u, 439u, 14u, 5u, 1u},
    {0xeb6c30u, 0x7c30u, 453u, 8u, 3u, 1u},
    {0xeaa4cau, 0xf4cau, 461u, 42u, 27u, 1u},
    {0xeb5131u, 0x6131u, 503u, 8u, 4u, 1u},
    {0xeb6c47u, 0x7c47u, 511u, 3u, 2u, 0u},
    {0xea82cau, 0xd2cau, 514u, 43u, 21u, 0u},
    {0xeaa52au, 0xf52au, 557u, 16u, 10u, 1u},
    {0xeb50c2u, 0x60c2u, 573u, 7u, 3u, 1u},
    {0xeb7822u, 0x8822u, 580u, 8u, 4u, 1u},
    {0xeb50ccu, 0x60ccu, 588u, 7u, 3u, 1u},
    {0xeb50d3u, 0x60d3u, 595u, 7u, 3u, 0u},
    {0xeb50dau, 0x60dau, 602u, 8u, 3u, 0u},
    {0xeb6c38u, 0x7c38u, 610u, 12u, 5u, 1u},
    {0xea8572u, 0xd572u, 622u, 20u, 13u, 0u},
    {0xeb5aa7u, 0x6aa7u, 642u, 7u, 3u, 0u},
    {0xeb5aaeu, 0x6aaeu, 649u, 8u, 3u, 0u},
    {0xea8596u, 0xd596u, 657u, 16u, 10u, 0u},
    {0xea8340u, 0xd340u, 673u, 9u, 5u, 0u},
    {0xea8349u, 0xd349u, 682u, 9u, 6u, 0u},
    {0xea8352u, 0xd352u, 691u, 11u, 8u, 0u},
    {0xea835du, 0xd35du, 702u, 5u, 4u, 0u},
    {0xeb5b02u, 0x6b02u, 707u, 3u, 1u, 0u},
    {0xeb5b1au, 0x6b1au, 710u, 39u, 17u, 1u},
    {0xeb5c18u, 0x6c18u, 749u, 32u, 12u, 1u},
    {0xeaa549u, 0xf549u, 781u, 116u, 62u, 1u},
    {0xeb002bu, 0x502bu, 897u, 84u, 45u, 0u},
    {0xeb8c8cu, 0x5c8cu, 981u, 39u, 16u, 1u},
    {0xeb8cb3u, 0x5cb3u, 1020u, 39u, 17u, 1u},
    {0xeb8cdau, 0x5cdau, 1059u, 11u, 5u, 1u},
    {0xeb8ce5u, 0x5ce5u, 1070u, 32u, 13u, 1u},
    {0xeb8d17u, 0x5d17u, 1102u, 39u, 17u, 1u},
    {0xeb8d99u, 0x5d99u, 1141u, 45u, 18u, 1u},
};

#elif defined(S6502_AOT_DEFINE_DISPATCH)

#define S6502_AOT_DISPATCH() do {                                      \
    switch (pc) {                                                        \
    case 0x6678u:                                      \
        if (s6502_aot_match(0u)) goto _aot_00;                \
        break;                                                         \
    case 0xf55bu:                                      \
        if (s6502_aot_match(1u)) goto _aot_01;                \
        break;                                                         \
    case 0x608au:                                      \
        S6502_AOT_ENTRY_608A_HOOK();                              \
        if (s6502_aot_match(2u)) goto _aot_02;                \
        break;                                                         \
    case 0x7937u:                                      \
        S6502_AOT_ENTRY_7937_HOOK();                              \
        if (s6502_aot_match(3u)) goto _aot_03;                \
        break;                                                         \
    case 0x6111u:                                      \
        if (s6502_aot_match(4u)) goto _aot_04;                \
        break;                                                         \
    case 0x650fu:                                      \
        S6502_AOT_ENTRY_650F_HOOK();                              \
        if (s6502_aot_match(5u)) goto _aot_05;                \
        break;                                                         \
    case 0x6a75u:                                      \
        S6502_AOT_ENTRY_6A75_HOOK();                              \
        if (s6502_aot_match(6u)) goto _aot_06;                \
        break;                                                         \
    case 0x6655u:                                      \
        if (s6502_aot_match(7u)) goto _aot_07;                \
        break;                                                         \
    case 0x7233u:                                      \
        if (s6502_aot_match(8u)) goto _aot_08;                \
        break;                                                         \
    case 0x6ae0u:                                      \
        if (s6502_aot_match(9u)) goto _aot_09;                \
        break;                                                         \
    case 0x882au:                                      \
        if (s6502_aot_match(10u)) goto _aot_10;                \
        break;                                                         \
    case 0x65a0u:                                      \
        if (s6502_aot_match(11u)) goto _aot_11;                \
        break;                                                         \
    case 0x7933u:                                      \
        if (s6502_aot_match(12u)) goto _aot_12;                \
        break;                                                         \
    case 0x6646u:                                      \
        if (s6502_aot_match(13u)) goto _aot_13;                \
        break;                                                         \
    case 0x7bd4u:                                      \
        if (s6502_aot_match(14u)) goto _aot_14;                \
        break;                                                         \
    case 0x7c30u:                                      \
        if (s6502_aot_match(15u)) goto _aot_15;                \
        break;                                                         \
    case 0xf4cau:                                      \
        if (s6502_aot_match(16u)) goto _aot_16;                \
        break;                                                         \
    case 0x6131u:                                      \
        if (s6502_aot_match(17u)) goto _aot_17;                \
        break;                                                         \
    case 0x7c47u:                                      \
        if (s6502_aot_match(18u)) goto _aot_18;                \
        break;                                                         \
    case 0xd2cau:                                      \
        if (s6502_aot_match(19u)) goto _aot_19;                \
        break;                                                         \
    case 0xf52au:                                      \
        if (s6502_aot_match(20u)) goto _aot_20;                \
        break;                                                         \
    case 0x60c2u:                                      \
        if (s6502_aot_match(21u)) goto _aot_21;                \
        break;                                                         \
    case 0x8822u:                                      \
        if (s6502_aot_match(22u)) goto _aot_22;                \
        break;                                                         \
    case 0x60ccu:                                      \
        if (s6502_aot_match(23u)) goto _aot_23;                \
        break;                                                         \
    case 0x60d3u:                                      \
        if (s6502_aot_match(24u)) goto _aot_24;                \
        break;                                                         \
    case 0x60dau:                                      \
        if (s6502_aot_match(25u)) goto _aot_25;                \
        break;                                                         \
    case 0x7c38u:                                      \
        if (s6502_aot_match(26u)) goto _aot_26;                \
        break;                                                         \
    case 0xd572u:                                      \
        if (s6502_aot_match(27u)) goto _aot_27;                \
        break;                                                         \
    case 0x6aa7u:                                      \
        if (s6502_aot_match(28u)) goto _aot_28;                \
        break;                                                         \
    case 0x6aaeu:                                      \
        if (s6502_aot_match(29u)) goto _aot_29;                \
        break;                                                         \
    case 0xd596u:                                      \
        if (s6502_aot_match(30u)) goto _aot_30;                \
        break;                                                         \
    case 0xd340u:                                      \
        if (s6502_aot_match(31u)) goto _aot_31;                \
        break;                                                         \
    case 0xd349u:                                      \
        if (s6502_aot_match(32u)) goto _aot_32;                \
        break;                                                         \
    case 0xd352u:                                      \
        if (s6502_aot_match(33u)) goto _aot_33;                \
        break;                                                         \
    case 0xd35du:                                      \
        if (s6502_aot_match(34u)) goto _aot_34;                \
        break;                                                         \
    case 0x6b02u:                                      \
        if (s6502_aot_match(35u)) goto _aot_35;                \
        break;                                                         \
    case 0x6b1au:                                      \
        if (s6502_aot_match(36u)) goto _aot_36;                \
        break;                                                         \
    case 0x6c18u:                                      \
        if (s6502_aot_match(37u)) goto _aot_37;                \
        break;                                                         \
    case 0xf549u:                                      \
        if (s6502_aot_match(38u)) goto _aot_38;                \
        break;                                                         \
    case 0x502bu:                                      \
        if (s6502_aot_match(39u)) goto _aot_39;                \
        break;                                                         \
    case 0x5c8cu:                                      \
        if (s6502_aot_match(40u)) goto _aot_40;                \
        break;                                                         \
    case 0x5cb3u:                                      \
        S6502_AOT_ENTRY_5CB3_HOOK();                              \
        if (s6502_aot_match(41u)) goto _aot_41;                \
        break;                                                         \
    case 0x5cdau:                                      \
        if (s6502_aot_match(42u)) goto _aot_42;                \
        break;                                                         \
    case 0x5ce5u:                                      \
        if (s6502_aot_match(43u)) goto _aot_43;                \
        break;                                                         \
    case 0x5d17u:                                      \
        if (s6502_aot_match(44u)) goto _aot_44;                \
        break;                                                         \
    case 0x5d99u:                                      \
        if (s6502_aot_match(45u)) goto _aot_45;                \
        break;                                                         \
    }                                                                      \
} while (0)
#define S6502_AOT_CHAIN(id, label) do {                                      \
    if ((executed >= cycles) || sys_halt_p()) goto _aot_return;              \
    if (s6502_aot_match(id)) goto label;                                     \
    goto _next;                                                              \
} while (0)
#define S6502_AOT_CHAIN_FAST(id, label) do {                                 \
    if ((executed >= cycles) || sys_halt_p()) goto _aot_return;              \
    if (s6502_aot_validation[id] == 1u) goto label;                          \
    if (s6502_aot_match(id)) goto label;                                     \
    goto _next;                                                              \
} while (0)
#define S6502_AOT_ZP_READ(addr) S6502_FAST_STACK_RAM[(uint8_t)(addr)]
#define S6502_AOT_RAM_READ(addr) S6502_FAST_STACK_RAM[(uint16_t)(addr)]
#define S6502_AOT_PAGE3_READ(addr) s6502_page3[(uint8_t)(addr)]
#define S6502_AOT_ZP16(addr) (                                              \
    (uint16_t)S6502_FAST_STACK_RAM[(uint8_t)(addr)] |                        \
    ((uint16_t)S6502_FAST_STACK_RAM[(uint8_t)((addr) + 1u)] << 8)            \
)
#define S6502_AOT_LDA(value, cost) do {                                      \
    ac = (uint8_t)(value); SET_NZ(ac); CYCLES(cost);                         \
} while (0)
#define S6502_AOT_LDY(value, cost) do {                                      \
    iy = (uint8_t)(value); SET_NZ(iy); CYCLES(cost);                         \
} while (0)
#define S6502_AOT_LDX(value, cost) do {                                      \
    ix = (uint8_t)(value); SET_NZ(ix); CYCLES(cost);                         \
} while (0)
#define S6502_AOT_STA(addr, cost) do {                                       \
    WRITE8((uint16_t)(addr), ac); CYCLES(cost);                              \
} while (0)
#define S6502_AOT_STX(addr, cost) do {                                       \
    WRITE8((uint16_t)(addr), ix); CYCLES(cost);                              \
} while (0)
#define S6502_AOT_STA_ZP(addr, cost) do {                                    \
    S6502_FAST_STACK_RAM[(uint8_t)(addr)] = ac; CYCLES(cost);                \
} while (0)
#define S6502_AOT_STX_ZP(addr, cost) do {                                    \
    S6502_FAST_STACK_RAM[(uint8_t)(addr)] = ix; CYCLES(cost);                \
} while (0)
#define S6502_AOT_STA_RAM(addr, cost) do {                                   \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = ac; CYCLES(cost);               \
} while (0)
#define S6502_AOT_STX_RAM(addr, cost) do {                                   \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = ix; CYCLES(cost);               \
} while (0)
#define S6502_AOT_LDA_INDY(base) do {                                        \
    et = (uint16_t)(base); ea = (uint16_t)(et + iy);                         \
    CYCLES((!!(0xff00 & (et ^ ea))));                                       \
    ac = READ8(ea); SET_NZ(ac); CYCLES(5);                                  \
} while (0)
#define S6502_AOT_STA_INDY(base) do {                                        \
    et = (uint16_t)(base); ea = (uint16_t)(et + iy);                         \
    WRITE8(ea, ac); CYCLES(6);                                               \
} while (0)
#define S6502_AOT_AND(value, cost) do {                                      \
    ac = (uint8_t)(ac & (uint8_t)(value)); SET_NZ(ac); CYCLES(cost);         \
} while (0)
#define S6502_AOT_AND_INDY(base) do {                                        \
    et = (uint16_t)(base); ea = (uint16_t)(et + iy);                         \
    CYCLES((!!(0xff00 & (et ^ ea))));                                       \
    ac = (uint8_t)(ac & READ8(ea)); SET_NZ(ac); CYCLES(5);                   \
} while (0)
#define S6502_AOT_ORA(value, cost) do {                                      \
    ac = (uint8_t)(ac | (uint8_t)(value)); SET_NZ(ac); CYCLES(cost);         \
} while (0)
#define S6502_AOT_COMPARE(reg, value, cost) do {                             \
    dt = (uint8_t)~(uint8_t)(value); et = (uint16_t)((reg) + dt + 1u);       \
    SET_C((et > 0xff)); SET_NZ((uint8_t)et); CYCLES(cost);                   \
} while (0)
#define S6502_AOT_CLC() do { SET_C(0); CYCLES(2); } while (0)
#define S6502_AOT_SEC() do { SET_C(1); CYCLES(2); } while (0)
#define S6502_AOT_SEI() do { SET_I(1); CYCLES(2); } while (0)
#define S6502_AOT_TAX() do { ix = ac; SET_NZ(ix); CYCLES(2); } while (0)
#define S6502_AOT_TAY() do { iy = ac; SET_NZ(iy); CYCLES(2); } while (0)
#define S6502_AOT_TXA() do { ac = ix; SET_NZ(ac); CYCLES(2); } while (0)
#define S6502_AOT_TYA() do { ac = iy; SET_NZ(ac); CYCLES(2); } while (0)
#define S6502_AOT_INY() do { iy += 1; SET_NZ(iy); CYCLES(2); } while (0)
#define S6502_AOT_INX() do { ix += 1; SET_NZ(ix); CYCLES(2); } while (0)
#define S6502_AOT_DEX() do { ix -= 1; SET_NZ(ix); CYCLES(2); } while (0)
#define S6502_AOT_DEY() do { iy -= 1; SET_NZ(iy); CYCLES(2); } while (0)
#define S6502_AOT_PHP() do { PUSH((status | FLAG_B | FLAG_U)); CYCLES(3); } while (0)
#define S6502_AOT_PHA() do { PUSH(ac); CYCLES(3); } while (0)
#define S6502_AOT_PLA() do { ac = POP(); SET_NZ(ac); CYCLES(4); } while (0)
#define S6502_AOT_PLP() do {                                                 \
    status = (uint8_t)(POP() | FLAG_U | FLAG_B); CYCLES(4);                  \
} while (0)
#define S6502_AOT_ASL_A() do {                                               \
    SET_C((0x80 & ac)); ac = (uint8_t)(ac << 1); SET_NZ(ac); CYCLES(2);      \
} while (0)
#define S6502_AOT_LSR_A() do {                                               \
    SET_C((0x01 & ac)); ac = (uint8_t)(ac >> 1); SET_NZ(ac); CYCLES(2);      \
} while (0)
#define S6502_AOT_ROL_A() do {                                               \
    dt = (uint8_t)(ac & 0x80); ac = (uint8_t)(CARRY | (ac << 1));            \
    SET_C(dt); SET_NZ(ac); CYCLES(2);                                        \
} while (0)
#define S6502_AOT_ROR_A() do {                                               \
    dt = (uint8_t)(ac & 0x01); ac = (uint8_t)((0x80 * CARRY) | (ac >> 1));  \
    SET_C(dt); SET_NZ(ac); CYCLES(2);                                        \
} while (0)
#define S6502_AOT_ASL_M(addr) do {                                           \
    dt = READ8((uint16_t)(addr)); SET_C((0x80 & dt));                        \
    dt = (uint8_t)(dt << 1); SET_NZ(dt); WRITE8((uint16_t)(addr), dt);       \
    CYCLES(6);                                                               \
} while (0)
#define S6502_AOT_ASL_M_RAM(addr) do {                                       \
    dt = S6502_AOT_RAM_READ(addr); SET_C((0x80 & dt));                       \
    dt = (uint8_t)(dt << 1); SET_NZ(dt);                                     \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(6);                  \
} while (0)
#define S6502_AOT_LSR_M(addr) do {                                           \
    dt = READ8((uint16_t)(addr)); SET_C((0x01 & dt));                        \
    dt = (uint8_t)(dt >> 1); SET_NZ(dt); WRITE8((uint16_t)(addr), dt);       \
    CYCLES(6);                                                               \
} while (0)
#define S6502_AOT_LSR_M_RAM(addr) do {                                       \
    dt = S6502_AOT_RAM_READ(addr); SET_C((0x01 & dt));                       \
    dt = (uint8_t)(dt >> 1); SET_NZ(dt);                                     \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(6);                  \
} while (0)
#define S6502_AOT_ROL_M(addr) do {                                           \
    dt = READ8((uint16_t)(addr)); et = (uint16_t)(dt & 0x80);               \
    dt = (uint8_t)(CARRY | (dt << 1)); SET_C(et); SET_NZ(dt);                \
    WRITE8((uint16_t)(addr), dt); CYCLES(6);                                 \
} while (0)
#define S6502_AOT_ROL_M_RAM(addr) do {                                       \
    dt = S6502_AOT_RAM_READ(addr); et = (uint16_t)(dt & 0x80);              \
    dt = (uint8_t)(CARRY | (dt << 1)); SET_C(et); SET_NZ(dt);                \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(6);                  \
} while (0)
#define S6502_AOT_ROR_M(addr) do {                                           \
    dt = READ8((uint16_t)(addr)); et = (uint16_t)(dt & 0x01);               \
    dt = (uint8_t)((0x80 * CARRY) | (dt >> 1)); SET_C(et); SET_NZ(dt);      \
    WRITE8((uint16_t)(addr), dt); CYCLES(6);                                \
} while (0)
#define S6502_AOT_ROR_M_RAM(addr) do {                                       \
    dt = S6502_AOT_RAM_READ(addr); et = (uint16_t)(dt & 0x01);              \
    dt = (uint8_t)((0x80 * CARRY) | (dt >> 1)); SET_C(et); SET_NZ(dt);      \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(6);                  \
} while (0)
#define S6502_AOT_INC(addr, cost) do {                                       \
    dt = (uint8_t)(READ8((uint16_t)(addr)) + 1); SET_NZ(dt);                 \
    WRITE8((uint16_t)(addr), dt); CYCLES(cost);                              \
} while (0)
#define S6502_AOT_INC_RAM(addr, cost) do {                                   \
    dt = (uint8_t)(S6502_AOT_RAM_READ(addr) + 1); SET_NZ(dt);                \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(cost);               \
} while (0)
#define S6502_AOT_DEC(addr, cost) do {                                       \
    dt = (uint8_t)(READ8((uint16_t)(addr)) - 1); SET_NZ(dt);                 \
    WRITE8((uint16_t)(addr), dt); CYCLES(cost);                              \
} while (0)
#define S6502_AOT_DEC_RAM(addr, cost) do {                                   \
    dt = (uint8_t)(S6502_AOT_RAM_READ(addr) - 1); SET_NZ(dt);                \
    S6502_FAST_STACK_RAM[(uint16_t)(addr)] = dt; CYCLES(cost);               \
} while (0)
#define S6502_AOT_ADC(value, cost) do {                                      \
    dt = (uint8_t)(value); CYCLES(cost);                                     \
    if (DECIMAL_p) {                                                         \
        uint8_t vu = (uint8_t)(dt & 0x0f);                                   \
        uint8_t vt = (uint8_t)((dt & 0xf0) >> 4);                            \
        uint8_t au = (uint8_t)(ac & 0x0f);                                   \
        uint8_t at = (uint8_t)((ac & 0xf0) >> 4);                            \
        uint8_t units = (uint8_t)(vu + au + CARRY);                          \
        uint8_t tens = (uint8_t)(vt + at);                                   \
        uint8_t tc = 0; CYCLES(1);                                           \
        if (units > 0x09) { tc = 1; tens += 1; units += 0x06; }              \
        if (tens > 0x09) tens += 0x06;                                       \
        if (at & 0x08) at |= 0xf0;                                           \
        if (vt & 0x08) vt |= 0xf0;                                           \
        { int8_t res = (int8_t)(at + vt + tc);                              \
          SET_V(((res < -8) || (res > 7))); }                                \
        ac = (uint8_t)((tens << 4) | (units & 0x0f)); SET_NZ(ac);            \
        SET_C((tens & 0xf0));                                                \
    } else {                                                                 \
        et = (uint16_t)(ac + dt + CARRY); SET_C((et > 0xff));                \
        SET_V(((ac ^ et) & (dt ^ et) & 0x80));                              \
        ac = (uint8_t)et; SET_NZ(ac);                                        \
    }                                                                        \
} while (0)
#define S6502_AOT_SBC(value, cost) do {                                      \
    dt = (uint8_t)(value); CYCLES(cost);                                     \
    if (DECIMAL_p) {                                                         \
        et = (uint16_t)(ac + ~dt + CARRY);                                   \
        ea = (uint16_t)(ac - dt - !CARRY); CYCLES(1);                        \
        if (ea & 0x8000) ea -= 0x60;                                         \
        if (((ac & 0x0f) - (dt & 0x0f) - !CARRY) & 0x8000) ea -= 0x06;      \
        SET_V(((ac ^ et) & (~dt ^ et) & 0x80));                              \
        SET_NZ((uint8_t)ea);                                                 \
        SET_C(((ea <= (uint16_t)ac) || ((ea & 0xff0) == 0xff0)));            \
        ac = (uint8_t)ea;                                                    \
    } else {                                                                 \
        dt = (uint8_t)~dt; et = (uint16_t)(ac + dt + CARRY);                 \
        SET_C((et > 0xff)); SET_V(((ac ^ et) & (dt ^ et) & 0x80));          \
        ac = (uint8_t)et; SET_NZ(ac);                                        \
    }                                                                        \
} while (0)
#define S6502_AOT_SBC_INDY(base) do {                                        \
    et = (uint16_t)(base); ea = (uint16_t)(et + iy);                         \
    CYCLES((!!(0xff00 & (et ^ ea))));                                       \
    S6502_AOT_SBC(READ8(ea), 5);                                             \
} while (0)
#define S6502_AOT_BRANCH(condition, fallthrough, target) do {                \
    pc = (uint16_t)(fallthrough);                                            \
    if (condition) {                                                         \
        CYCLES(1); CYCLES((!!(0xff00 & (pc ^ (uint16_t)(target)))));         \
        pc = (uint16_t)(target);                                             \
    }                                                                        \
    CYCLES(2); goto _exit;                                                   \
} while (0)
#define S6502_AOT_BRANCH_TARGET(chain, condition, fallthrough, target, id, label) do { \
    pc = (uint16_t)(fallthrough);                                            \
    if (condition) {                                                         \
        CYCLES(1); CYCLES((!!(0xff00 & (pc ^ (uint16_t)(target)))));         \
        pc = (uint16_t)(target); CYCLES(2); chain(id, label);                \
    }                                                                        \
    CYCLES(2); goto _exit;                                                   \
} while (0)
#define S6502_AOT_BRANCH_FALL(chain, condition, fallthrough, target, id, label) do { \
    pc = (uint16_t)(fallthrough);                                            \
    if (condition) {                                                         \
        CYCLES(1); CYCLES((!!(0xff00 & (pc ^ (uint16_t)(target)))));         \
        pc = (uint16_t)(target); CYCLES(2); goto _exit;                      \
    }                                                                        \
    CYCLES(2); chain(id, label);                                             \
} while (0)
#define S6502_AOT_BRANCH_BOTH(fall_chain, target_chain, condition, fallthrough, target, fall_id, fall_label, target_id, target_label) do { \
    pc = (uint16_t)(fallthrough);                                            \
    if (condition) {                                                         \
        CYCLES(1); CYCLES((!!(0xff00 & (pc ^ (uint16_t)(target)))));         \
        pc = (uint16_t)(target); CYCLES(2);                                  \
        target_chain(target_id, target_label);                              \
    }                                                                        \
    CYCLES(2); fall_chain(fall_id, fall_label);                              \
} while (0)
#define S6502_AOT_JSR(return_pc, target) do {                                \
    PUSH((uint16_t)(return_pc) >> 8); PUSH((uint16_t)(return_pc) & 0xff);    \
    pc = (uint16_t)(target); CYCLES(6); goto _exit;                          \
} while (0)
#define S6502_AOT_JSR_CHAIN(chain, return_pc, target, id, label) do {        \
    PUSH((uint16_t)(return_pc) >> 8); PUSH((uint16_t)(return_pc) & 0xff);    \
    pc = (uint16_t)(target); CYCLES(6); chain(id, label);                    \
} while (0)
#define S6502_AOT_JMP(target) do {                                           \
    pc = (uint16_t)(target); CYCLES(3); goto _exit;                          \
} while (0)
#define S6502_AOT_JMP_CHAIN(chain, target, id, label) do {                   \
    pc = (uint16_t)(target); CYCLES(3); chain(id, label);                    \
} while (0)
#define S6502_AOT_RTS() do {                                                 \
    pc = POP(); pc = (uint16_t)(pc | (POP() << 8)); pc += 1;                \
    CYCLES(6); goto _exit;                                                   \
} while (0)

#elif defined(S6502_AOT_EMIT_BLOCKS)
  _aot_00:
    S6502_AOT_HIT(0u, 15u);
    S6502_AOT_SEC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3au), 4);
    S6502_AOT_SBC(0x20u, 2);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_SBC(0x00u, 2);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_SEC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x38u), 4);
    S6502_AOT_SBC(0x20u, 2);
    S6502_AOT_STA_ZP(0x38u, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x39u), 4);
    S6502_AOT_SBC(0x00u, 2);
    S6502_AOT_STA_ZP(0x39u, 4);
    S6502_AOT_RTS();

  _aot_01:
    S6502_AOT_HIT(1u, 55u);
    S6502_AOT_LDA(0x05u, 2);
    S6502_AOT_STA(0x000cu, 3);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_ASL_A();
    S6502_AOT_TAX();
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ROL_A();
    S6502_AOT_TAY();
    S6502_AOT_TXA();
    S6502_AOT_ASL_A();
    S6502_AOT_TAX();
    S6502_AOT_TYA();
    S6502_AOT_ROL_A();
    S6502_AOT_TAY();
    S6502_AOT_TXA();
    S6502_AOT_CLC();
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2001u), 4);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_TYA();
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2002u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_PLA();
    S6502_AOT_TAY();
    S6502_AOT_PLA();
    S6502_AOT_TAX();
    S6502_AOT_PLP();
    S6502_AOT_RTS();

  _aot_02:
    S6502_AOT_HIT(2u, 16u);
    S6502_AOT_TXA();
    S6502_AOT_TAY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20b3u, 4);
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20b4u, 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_RAM(0x20b5u, 4);
    S6502_AOT_LDY(S6502_AOT_RAM_READ(0x208bu), 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_LDA(0xffu, 2);
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_COMPARE(iy, 0x00u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, ZERO_p, 0x60adu, 0x60c2u, 21u, _aot_21);

  _aot_03:
    S6502_AOT_HIT(3u, 5u);
    S6502_AOT_LDA(READ8(0x0003u), 3);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_INY();
    S6502_AOT_DEX();
    S6502_AOT_JMP_CHAIN(S6502_AOT_CHAIN, 0x7933u, 12u, _aot_12);

  _aot_04:
    S6502_AOT_HIT(4u, 14u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_AND(S6502_AOT_RAM_READ(0x20e5u), 4);
    S6502_AOT_ORA(S6502_AOT_RAM_READ(0x20b3u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_INY();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20b4u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_AND(S6502_AOT_RAM_READ(0x20e6u), 4);
    S6502_AOT_ORA(S6502_AOT_RAM_READ(0x20b5u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_JSR_CHAIN(S6502_AOT_CHAIN, 0x6130u, 0x6646u, 13u, _aot_13);

  _aot_05:
    S6502_AOT_HIT(5u, 13u);
    S6502_AOT_TXA();
    S6502_AOT_TAY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20b3u, 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_RAM(0x20b4u, 4);
    S6502_AOT_LDY(S6502_AOT_RAM_READ(0x208bu), 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_LDA(0xffu, 2);
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_COMPARE(iy, 0x00u, 2);
    S6502_AOT_BRANCH(ZERO_p, 0x652cu, 0x653fu);

  _aot_06:
    S6502_AOT_HIT(6u, 17u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20cfu), 4);
    S6502_AOT_TAX();
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, ZERO_p, 0x6a9cu, 0x6aa7u, 28u, _aot_28);

  _aot_07:
    S6502_AOT_HIT(7u, 15u);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3au), 4);
    S6502_AOT_ADC(0x20u, 2);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x38u), 4);
    S6502_AOT_ADC(0x20u, 2);
    S6502_AOT_STA_ZP(0x38u, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x39u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x39u, 4);
    S6502_AOT_RTS();

  _aot_08:
    S6502_AOT_HIT(8u, 14u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3au), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_DEC_RAM(0x20d8u, 6);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20d8u), 4);
    S6502_AOT_COMPARE(ac, 0x00u, 2);
    S6502_AOT_BRANCH(!ZERO_p, 0x7254u, 0x71fbu);

  _aot_09:
    S6502_AOT_HIT(9u, 14u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20e6u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3au), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_DEC_RAM(0x20d8u, 6);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20d8u), 4);
    S6502_AOT_COMPARE(ac, 0x00u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN, ZERO_p, 0x6b02u, 0x6b05u, 35u, _aot_35);

  _aot_10:
    S6502_AOT_HIT(10u, 9u);
    S6502_AOT_STA_RAM(0x20b7u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(0x01u, 2);
    S6502_AOT_ADC(S6502_AOT_ZP_READ(0x3au), 4);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_JMP_CHAIN(S6502_AOT_CHAIN_FAST, 0x8822u, 22u, _aot_22);

  _aot_11:
    S6502_AOT_HIT(11u, 11u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_AND(S6502_AOT_RAM_READ(0x20e5u), 4);
    S6502_AOT_ORA(S6502_AOT_RAM_READ(0x20b3u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_AND(S6502_AOT_RAM_READ(0x20e6u), 4);
    S6502_AOT_ORA(S6502_AOT_RAM_READ(0x20b4u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x3au));
    S6502_AOT_JSR_CHAIN(S6502_AOT_CHAIN, 0x65b9u, 0x6646u, 13u, _aot_13);

  _aot_12:
    S6502_AOT_HIT(12u, 2u);
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, ZERO_p, 0x7937u, 0x7940u, 3u, _aot_03);

  _aot_13:
    S6502_AOT_HIT(13u, 3u);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2082u), 4);
    S6502_AOT_COMPARE(ac, 0x40u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, !CARRY_p, 0x664du, 0x6678u, 0u, _aot_00);

  _aot_14:
    S6502_AOT_HIT(14u, 5u);
    S6502_AOT_ASL_M_RAM(0x2089u);
    S6502_AOT_ROL_M_RAM(0x208au);
    S6502_AOT_ROL_M_RAM(0x2085u);
    S6502_AOT_ROL_M_RAM(0x2086u);
    S6502_AOT_BRANCH(!CARRY_p, 0x7be2u, 0x7bfau);

  _aot_15:
    S6502_AOT_HIT(15u, 3u);
    S6502_AOT_ASL_M_RAM(0x2089u);
    S6502_AOT_ROL_M_RAM(0x2085u);
    S6502_AOT_BRANCH_BOTH(S6502_AOT_CHAIN_FAST, S6502_AOT_CHAIN_FAST, !CARRY_p, 0x7c38u, 0x7c47u, 26u, _aot_26, 18u, _aot_18);

  _aot_16:
    S6502_AOT_HIT(16u, 27u);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_SEC();
    S6502_AOT_SBC(S6502_AOT_PAGE3_READ(0x03d6u), 4);
    S6502_AOT_TAX();
    S6502_AOT_LDA(READ8(0x000eu), 3);
    S6502_AOT_SBC(S6502_AOT_PAGE3_READ(0x03d5u), 4);
    S6502_AOT_LSR_A();
    S6502_AOT_TAY();
    S6502_AOT_TXA();
    S6502_AOT_ROR_A();
    S6502_AOT_TAX();
    S6502_AOT_TYA();
    S6502_AOT_LSR_A();
    S6502_AOT_TXA();
    S6502_AOT_ROR_A();
    S6502_AOT_CLC();
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_PLA();
    S6502_AOT_TAY();
    S6502_AOT_PLA();
    S6502_AOT_TAX();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_PLP();
    S6502_AOT_RTS();

  _aot_17:
    S6502_AOT_HIT(17u, 4u);
    S6502_AOT_INC_RAM(0x2082u, 6);
    S6502_AOT_INX();
    S6502_AOT_INX();
    S6502_AOT_JMP(0x6086u);

  _aot_18:
    S6502_AOT_HIT(18u, 2u);
    S6502_AOT_DEY();
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN, !ZERO_p, 0x7c4au, 0x7c30u, 15u, _aot_15);

  _aot_19:
    S6502_AOT_HIT(19u, 21u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x20u));
    S6502_AOT_AND_INDY(S6502_AOT_ZP16(0x23u));
    S6502_AOT_LDY(0x08u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x2au));
    S6502_AOT_LDY(0x01u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x20u));
    S6502_AOT_AND_INDY(S6502_AOT_ZP16(0x23u));
    S6502_AOT_LDY(0x09u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x2au));
    S6502_AOT_LDY(0x02u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x20u));
    S6502_AOT_AND_INDY(S6502_AOT_ZP16(0x23u));
    S6502_AOT_LDY(0x0au, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x2au));
    S6502_AOT_LDY(0x03u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x20u));
    S6502_AOT_AND_INDY(S6502_AOT_ZP16(0x23u));
    S6502_AOT_LDY(0x0bu, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x2au));
    S6502_AOT_JSR_CHAIN(S6502_AOT_CHAIN, 0xd2f4u, 0xd596u, 30u, _aot_30);

  _aot_20:
    S6502_AOT_HIT(20u, 10u);
    S6502_AOT_PHP();
    S6502_AOT_SEI();
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_TXA();
    S6502_AOT_PHA();
    S6502_AOT_TYA();
    S6502_AOT_PHA();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_COMPARE(ac, 0xe0u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, CARRY_p, 0xf53au, 0xf549u, 38u, _aot_38);

  _aot_21:
    S6502_AOT_HIT(21u, 3u);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2081u), 4);
    S6502_AOT_COMPARE(ac, 0x90u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, !ZERO_p, 0x60c9u, 0x60ccu, 23u, _aot_23);

  _aot_22:
    S6502_AOT_HIT(22u, 4u);
    S6502_AOT_SEC();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20b7u), 4);
    S6502_AOT_SBC(0x08u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, !CARRY_p, 0x882au, 0x8887u, 10u, _aot_10);

  _aot_23:
    S6502_AOT_HIT(23u, 3u);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2081u), 4);
    S6502_AOT_COMPARE(ac, 0x08u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, !CARRY_p, 0x60d3u, 0x6139u, 24u, _aot_24);

  _aot_24:
    S6502_AOT_HIT(24u, 3u);
    S6502_AOT_LDA(S6502_AOT_PAGE3_READ(0x03e5u), 4);
    S6502_AOT_COMPARE(ac, 0x01u, 2);
    S6502_AOT_BRANCH_BOTH(S6502_AOT_CHAIN_FAST, S6502_AOT_CHAIN, !ZERO_p, 0x60dau, 0x6111u, 25u, _aot_25, 4u, _aot_04);

  _aot_25:
    S6502_AOT_HIT(25u, 3u);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_COMPARE(ac, S6502_AOT_PAGE3_READ(0x03e7u), 4);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN, !ZERO_p, 0x60e2u, 0x6111u, 4u, _aot_04);

  _aot_26:
    S6502_AOT_HIT(26u, 5u);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2087u), 4);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2089u), 4);
    S6502_AOT_STA_RAM(0x2089u, 4);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN_FAST, !CARRY_p, 0x7c44u, 0x7c47u, 18u, _aot_18);

  _aot_27:
    S6502_AOT_HIT(27u, 13u);
    S6502_AOT_TAY();
    S6502_AOT_SEC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x26u), 3);
    S6502_AOT_SBC(0x01u, 2);
    S6502_AOT_STA_ZP(0x26u, 3);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x27u), 3);
    S6502_AOT_SBC(0x00u, 2);
    S6502_AOT_STA_ZP(0x27u, 3);
    S6502_AOT_PHA();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x26u), 3);
    S6502_AOT_PHA();
    S6502_AOT_TYA();
    S6502_AOT_RTS();

  _aot_28:
    S6502_AOT_HIT(28u, 3u);
    S6502_AOT_LDA(S6502_AOT_PAGE3_READ(0x03e5u), 4);
    S6502_AOT_COMPARE(ac, 0x01u, 2);
    S6502_AOT_BRANCH_BOTH(S6502_AOT_CHAIN_FAST, S6502_AOT_CHAIN, !ZERO_p, 0x6aaeu, 0x6ae0u, 29u, _aot_29, 9u, _aot_09);

  _aot_29:
    S6502_AOT_HIT(29u, 3u);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x3bu), 4);
    S6502_AOT_COMPARE(ac, S6502_AOT_PAGE3_READ(0x03e7u), 4);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN, !ZERO_p, 0x6ab6u, 0x6ae0u, 9u, _aot_09);

  _aot_30:
    S6502_AOT_HIT(30u, 10u);
    S6502_AOT_PHA();
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2au), 3);
    S6502_AOT_ADC(0x08u, 2);
    S6502_AOT_STA_ZP(0x20u, 3);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2bu), 3);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x21u, 3);
    S6502_AOT_PLA();
    S6502_AOT_RTS();

  _aot_31:
    S6502_AOT_HIT(31u, 5u);
    S6502_AOT_LDX(0x00u, 2);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x20u), 3);
    S6502_AOT_SEC();
    S6502_AOT_SBC(S6502_AOT_ZP_READ(0x23u), 3);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, ZERO_p, 0xd349u, 0xd34cu, 32u, _aot_32);

  _aot_32:
    S6502_AOT_HIT(32u, 6u);
    S6502_AOT_PHP();
    S6502_AOT_INX();
    S6502_AOT_PLP();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x21u), 3);
    S6502_AOT_SBC(S6502_AOT_ZP_READ(0x24u), 3);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, ZERO_p, 0xd352u, 0xd355u, 33u, _aot_33);

  _aot_33:
    S6502_AOT_HIT(33u, 8u);
    S6502_AOT_PHP();
    S6502_AOT_INX();
    S6502_AOT_PLP();
    S6502_AOT_PHP();
    S6502_AOT_PLA();
    S6502_AOT_ORA(0x02u, 2);
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN_FAST, ZERO_p, 0xd35du, 0xd35fu, 34u, _aot_34);

  _aot_34:
    S6502_AOT_HIT(34u, 4u);
    S6502_AOT_AND(0xfdu, 2);
    S6502_AOT_PHA();
    S6502_AOT_PLP();
    S6502_AOT_RTS();

  _aot_35:
    S6502_AOT_HIT(35u, 1u);
    S6502_AOT_JMP_CHAIN(S6502_AOT_CHAIN, 0x6a75u, 6u, _aot_06);

  _aot_36:
    S6502_AOT_HIT(36u, 17u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20cfu), 4);
    S6502_AOT_TAX();
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH(ZERO_p, 0x6b41u, 0x6b4cu);

  _aot_37:
    S6502_AOT_HIT(37u, 12u);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20e9u), 4);
    S6502_AOT_STA_ZP(0x3au, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20eau), 4);
    S6502_AOT_STA_ZP(0x3bu, 4);
    S6502_AOT_JSR_CHAIN(S6502_AOT_CHAIN_FAST, 0x6c37u, 0x6646u, 13u, _aot_13);

  _aot_38:
    S6502_AOT_HIT(38u, 62u);
    S6502_AOT_SEC();
    S6502_AOT_SBC(0xe0u, 2);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2029u), 4);
    S6502_AOT_STA_RAM(0x2001u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x202au), 4);
    S6502_AOT_STA_RAM(0x2002u, 4);
    S6502_AOT_LDA(0x05u, 2);
    S6502_AOT_STA(0x000cu, 3);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_ASL_A();
    S6502_AOT_TAX();
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ROL_A();
    S6502_AOT_TAY();
    S6502_AOT_TXA();
    S6502_AOT_ASL_A();
    S6502_AOT_TAX();
    S6502_AOT_TYA();
    S6502_AOT_ROL_A();
    S6502_AOT_TAY();
    S6502_AOT_TXA();
    S6502_AOT_CLC();
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2001u), 4);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_TYA();
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2002u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_LDA(READ8(0x000du), 3);
    S6502_AOT_INC(0x0cu, 5);
    S6502_AOT_CLC();
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA(0x000du, 3);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_RAM_READ(0x2000u), 4);
    S6502_AOT_STA(0x000eu, 3);
    S6502_AOT_STA_RAM(0x2000u, 4);
    S6502_AOT_PLA();
    S6502_AOT_TAY();
    S6502_AOT_PLA();
    S6502_AOT_TAX();
    S6502_AOT_PLP();
    S6502_AOT_RTS();

  _aot_39:
    S6502_AOT_HIT(39u, 45u);
    S6502_AOT_LDY(0x02u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_STA_ZP(0x20u, 3);
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_STA_ZP(0x21u, 3);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x20u), 3);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_INY();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x21u), 3);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x20u), 3);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x20u, 3);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x21u), 3);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x21u, 3);
    S6502_AOT_LDY(0x02u, 2);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x20u), 3);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_INY();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x21u), 3);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_STA_ZP(0x23u, 3);
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_STA_ZP(0x24u, 3);
    S6502_AOT_LDY(0x06u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x23u));
    S6502_AOT_LDY(0x04u, 2);
    S6502_AOT_SEC();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_SBC(0x01u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_INY();
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_SBC(0x00u, 2);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x28u));
    S6502_AOT_JMP(0x5010u);

  _aot_40:
    S6502_AOT_HIT(40u, 16u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x31u));
    S6502_AOT_AND(S6502_AOT_RAM_READ(0x20e3u), 4);
    S6502_AOT_ORA(S6502_AOT_RAM_READ(0x20e6u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x31u));
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x31u), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x31u, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x32u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x32u, 4);
    S6502_AOT_DEC_RAM(0x20d8u, 6);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20d8u), 4);
    S6502_AOT_COMPARE(ac, 0x00u, 2);
    S6502_AOT_BRANCH_FALL(S6502_AOT_CHAIN, ZERO_p, 0x5cb3u, 0x5d05u, 41u, _aot_41);

  _aot_41:
    S6502_AOT_HIT(41u, 17u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20cfu), 4);
    S6502_AOT_TAX();
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH_BOTH(S6502_AOT_CHAIN_FAST, S6502_AOT_CHAIN_FAST, ZERO_p, 0x5cdau, 0x5ce5u, 42u, _aot_42, 43u, _aot_43);

  _aot_42:
    S6502_AOT_HIT(42u, 5u);
    S6502_AOT_LSR_M_RAM(0x20e5u);
    S6502_AOT_ROR_M_RAM(0x20e6u);
    S6502_AOT_DEX();
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH_BOTH(S6502_AOT_CHAIN_FAST, S6502_AOT_CHAIN_FAST, !ZERO_p, 0x5ce5u, 0x5cdau, 43u, _aot_43, 42u, _aot_42);

  _aot_43:
    S6502_AOT_HIT(43u, 13u);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20e6u), 4);
    S6502_AOT_STA_INDY(S6502_AOT_ZP16(0x31u));
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x31u), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x31u, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x32u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x32u, 4);
    S6502_AOT_DEC_RAM(0x20d8u, 6);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20d8u), 4);
    S6502_AOT_COMPARE(ac, 0x00u, 2);
    S6502_AOT_BRANCH_TARGET(S6502_AOT_CHAIN, !ZERO_p, 0x5d05u, 0x5cb3u, 41u, _aot_41);

  _aot_44:
    S6502_AOT_HIT(44u, 17u);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e5u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_LDY(0x00u, 2);
    S6502_AOT_LDA_INDY(S6502_AOT_ZP16(0x2fu));
    S6502_AOT_STA_RAM(0x20e6u, 4);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20cfu), 4);
    S6502_AOT_TAX();
    S6502_AOT_COMPARE(ix, 0x00u, 2);
    S6502_AOT_BRANCH(ZERO_p, 0x5d3eu, 0x5d49u);

  _aot_45:
    S6502_AOT_HIT(45u, 18u);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x2fu), 4);
    S6502_AOT_ADC(0x01u, 2);
    S6502_AOT_STA_ZP(0x2fu, 4);
    S6502_AOT_LDA(S6502_AOT_ZP_READ(0x30u), 4);
    S6502_AOT_ADC(0x00u, 2);
    S6502_AOT_STA_ZP(0x30u, 4);
    S6502_AOT_CLC();
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20deu), 4);
    S6502_AOT_ADC(S6502_AOT_ZP_READ(0x31u), 4);
    S6502_AOT_STA_ZP(0x31u, 4);
    S6502_AOT_LDA(0x00u, 2);
    S6502_AOT_ADC(S6502_AOT_ZP_READ(0x32u), 4);
    S6502_AOT_STA_ZP(0x32u, 4);
    S6502_AOT_DEC_RAM(0x20dau, 6);
    S6502_AOT_LDA(S6502_AOT_RAM_READ(0x20dau), 4);
    S6502_AOT_COMPARE(ac, 0x00u, 2);
    S6502_AOT_BRANCH(ZERO_p, 0x5dc6u, 0x5dc9u);

#elif defined(S6502_AOT_UNDEFINE)
#undef S6502_AOT_DISPATCH
#undef S6502_AOT_CHAIN
#undef S6502_AOT_CHAIN_FAST
#undef S6502_AOT_ZP_READ
#undef S6502_AOT_RAM_READ
#undef S6502_AOT_PAGE3_READ
#undef S6502_AOT_ZP16
#undef S6502_AOT_LDA
#undef S6502_AOT_LDY
#undef S6502_AOT_LDX
#undef S6502_AOT_STA
#undef S6502_AOT_STX
#undef S6502_AOT_STA_ZP
#undef S6502_AOT_STX_ZP
#undef S6502_AOT_STA_RAM
#undef S6502_AOT_STX_RAM
#undef S6502_AOT_LDA_INDY
#undef S6502_AOT_STA_INDY
#undef S6502_AOT_AND
#undef S6502_AOT_AND_INDY
#undef S6502_AOT_ORA
#undef S6502_AOT_COMPARE
#undef S6502_AOT_CLC
#undef S6502_AOT_SEC
#undef S6502_AOT_SEI
#undef S6502_AOT_TAX
#undef S6502_AOT_TAY
#undef S6502_AOT_TXA
#undef S6502_AOT_TYA
#undef S6502_AOT_INY
#undef S6502_AOT_INX
#undef S6502_AOT_DEX
#undef S6502_AOT_DEY
#undef S6502_AOT_PHP
#undef S6502_AOT_PHA
#undef S6502_AOT_PLA
#undef S6502_AOT_PLP
#undef S6502_AOT_ASL_A
#undef S6502_AOT_LSR_A
#undef S6502_AOT_ROL_A
#undef S6502_AOT_ROR_A
#undef S6502_AOT_ASL_M
#undef S6502_AOT_ASL_M_RAM
#undef S6502_AOT_LSR_M
#undef S6502_AOT_LSR_M_RAM
#undef S6502_AOT_ROL_M
#undef S6502_AOT_ROL_M_RAM
#undef S6502_AOT_INC
#undef S6502_AOT_ROR_M
#undef S6502_AOT_ROR_M_RAM
#undef S6502_AOT_INC_RAM
#undef S6502_AOT_DEC
#undef S6502_AOT_DEC_RAM
#undef S6502_AOT_ADC
#undef S6502_AOT_SBC
#undef S6502_AOT_SBC_INDY
#undef S6502_AOT_BRANCH
#undef S6502_AOT_BRANCH_TARGET
#undef S6502_AOT_BRANCH_FALL
#undef S6502_AOT_BRANCH_BOTH
#undef S6502_AOT_JSR
#undef S6502_AOT_JSR_CHAIN
#undef S6502_AOT_JMP
#undef S6502_AOT_JMP_CHAIN
#undef S6502_AOT_RTS
#endif
